### PR TITLE
Katana

### PR DESCRIPTION
**Pull request by AbelGamerC**
Version 0.13.0

### CODE REVIEW

**Comment by legoboy0215** [comment]
It does not work like that -_-

**Comment by legoboy0215** [comment]
Better close it.

**Comment by AbelGamerC** [comment]
??

**Comment by legoboy0215** [comment]
You need to update all other stuff too, not only version.

**Comment by AbelGamerC** [comment]
also that I do

**Comment by AbelGamerC** [comment]
also that I do

**Comment by legoboy0215** [comment]
CLOSE it, and please stop duplicating Pull Request. You don't know what you are doing.

**Comment by AbelGamerC** [comment]
-.- If so please let me work

**Pull request closed without merging**
